spring.application.name=demo-alicorp
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=AlicorpDemoBD;encrypt=true;trustServerCertificate=true

spring.datasource.username=nabia
spring.datasource.password=mWs09CjTH

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

jwt.secret=mi_clave_muy_larga_y_segura_32_bytes_minimo